server:
  port: 11113
  servlet:
    context-path: /
spring:
  application:
    name: xuegao-im-wangzaiovo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: debug
    cn.jay.repository: trace
#    com.xuegao.springboot_tool.dao: debug

